#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="RootDB")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region 可扩展性方法定义
  partial void OnCreated();
  partial void Inserttb_Admin(tb_Admin instance);
  partial void Updatetb_Admin(tb_Admin instance);
  partial void Deletetb_Admin(tb_Admin instance);
  partial void Inserttb_BookInfo(tb_BookInfo instance);
  partial void Updatetb_BookInfo(tb_BookInfo instance);
  partial void Deletetb_BookInfo(tb_BookInfo instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["RootDBConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<tb_Admin> tb_Admin
	{
		get
		{
			return this.GetTable<tb_Admin>();
		}
	}
	
	public System.Data.Linq.Table<tb_BookInfo> tb_BookInfo
	{
		get
		{
			return this.GetTable<tb_BookInfo>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_Admin")]
public partial class tb_Admin : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _AdminID;
	
	private string _AdminName;
	
	private string _PassWord;
	
	private string _RealName;
	
	private string _Email;
	
	private System.DateTime _LoadDate;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAdminIDChanging(int value);
    partial void OnAdminIDChanged();
    partial void OnAdminNameChanging(string value);
    partial void OnAdminNameChanged();
    partial void OnPassWordChanging(string value);
    partial void OnPassWordChanged();
    partial void OnRealNameChanging(string value);
    partial void OnRealNameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnLoadDateChanging(System.DateTime value);
    partial void OnLoadDateChanged();
    #endregion
	
	public tb_Admin()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int AdminID
	{
		get
		{
			return this._AdminID;
		}
		set
		{
			if ((this._AdminID != value))
			{
				this.OnAdminIDChanging(value);
				this.SendPropertyChanging();
				this._AdminID = value;
				this.SendPropertyChanged("AdminID");
				this.OnAdminIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string AdminName
	{
		get
		{
			return this._AdminName;
		}
		set
		{
			if ((this._AdminName != value))
			{
				this.OnAdminNameChanging(value);
				this.SendPropertyChanging();
				this._AdminName = value;
				this.SendPropertyChanged("AdminName");
				this.OnAdminNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassWord", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string PassWord
	{
		get
		{
			return this._PassWord;
		}
		set
		{
			if ((this._PassWord != value))
			{
				this.OnPassWordChanging(value);
				this.SendPropertyChanging();
				this._PassWord = value;
				this.SendPropertyChanged("PassWord");
				this.OnPassWordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RealName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string RealName
	{
		get
		{
			return this._RealName;
		}
		set
		{
			if ((this._RealName != value))
			{
				this.OnRealNameChanging(value);
				this.SendPropertyChanging();
				this._RealName = value;
				this.SendPropertyChanged("RealName");
				this.OnRealNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoadDate", DbType="DateTime NOT NULL")]
	public System.DateTime LoadDate
	{
		get
		{
			return this._LoadDate;
		}
		set
		{
			if ((this._LoadDate != value))
			{
				this.OnLoadDateChanging(value);
				this.SendPropertyChanging();
				this._LoadDate = value;
				this.SendPropertyChanged("LoadDate");
				this.OnLoadDateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_BookInfo")]
public partial class tb_BookInfo : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _BookID;
	
	private int _ClassID;
	
	private string _BookName;
	
	private string _BookIntroduce;
	
	private string _Author;
	
	private string _Company;
	
	private double _MarketPrice;
	
	private double _HotPrice;
	
	private bool _Isrefinement;
	
	private bool _IsHot;
	
	private bool _IsDiscount;
	
	private System.DateTime _LoadDate;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBookIDChanging(int value);
    partial void OnBookIDChanged();
    partial void OnClassIDChanging(int value);
    partial void OnClassIDChanged();
    partial void OnBookNameChanging(string value);
    partial void OnBookNameChanged();
    partial void OnBookIntroduceChanging(string value);
    partial void OnBookIntroduceChanged();
    partial void OnAuthorChanging(string value);
    partial void OnAuthorChanged();
    partial void OnCompanyChanging(string value);
    partial void OnCompanyChanged();
    partial void OnMarketPriceChanging(double value);
    partial void OnMarketPriceChanged();
    partial void OnHotPriceChanging(double value);
    partial void OnHotPriceChanged();
    partial void OnIsrefinementChanging(bool value);
    partial void OnIsrefinementChanged();
    partial void OnIsHotChanging(bool value);
    partial void OnIsHotChanged();
    partial void OnIsDiscountChanging(bool value);
    partial void OnIsDiscountChanged();
    partial void OnLoadDateChanging(System.DateTime value);
    partial void OnLoadDateChanged();
    #endregion
	
	public tb_BookInfo()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int BookID
	{
		get
		{
			return this._BookID;
		}
		set
		{
			if ((this._BookID != value))
			{
				this.OnBookIDChanging(value);
				this.SendPropertyChanging();
				this._BookID = value;
				this.SendPropertyChanged("BookID");
				this.OnBookIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassID", DbType="Int NOT NULL")]
	public int ClassID
	{
		get
		{
			return this._ClassID;
		}
		set
		{
			if ((this._ClassID != value))
			{
				this.OnClassIDChanging(value);
				this.SendPropertyChanging();
				this._ClassID = value;
				this.SendPropertyChanged("ClassID");
				this.OnClassIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string BookName
	{
		get
		{
			return this._BookName;
		}
		set
		{
			if ((this._BookName != value))
			{
				this.OnBookNameChanging(value);
				this.SendPropertyChanging();
				this._BookName = value;
				this.SendPropertyChanged("BookName");
				this.OnBookNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookIntroduce", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
	public string BookIntroduce
	{
		get
		{
			return this._BookIntroduce;
		}
		set
		{
			if ((this._BookIntroduce != value))
			{
				this.OnBookIntroduceChanging(value);
				this.SendPropertyChanging();
				this._BookIntroduce = value;
				this.SendPropertyChanged("BookIntroduce");
				this.OnBookIntroduceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Author", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Author
	{
		get
		{
			return this._Author;
		}
		set
		{
			if ((this._Author != value))
			{
				this.OnAuthorChanging(value);
				this.SendPropertyChanging();
				this._Author = value;
				this.SendPropertyChanged("Author");
				this.OnAuthorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Company
	{
		get
		{
			return this._Company;
		}
		set
		{
			if ((this._Company != value))
			{
				this.OnCompanyChanging(value);
				this.SendPropertyChanging();
				this._Company = value;
				this.SendPropertyChanged("Company");
				this.OnCompanyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MarketPrice", DbType="Float NOT NULL")]
	public double MarketPrice
	{
		get
		{
			return this._MarketPrice;
		}
		set
		{
			if ((this._MarketPrice != value))
			{
				this.OnMarketPriceChanging(value);
				this.SendPropertyChanging();
				this._MarketPrice = value;
				this.SendPropertyChanged("MarketPrice");
				this.OnMarketPriceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HotPrice", DbType="Float NOT NULL")]
	public double HotPrice
	{
		get
		{
			return this._HotPrice;
		}
		set
		{
			if ((this._HotPrice != value))
			{
				this.OnHotPriceChanging(value);
				this.SendPropertyChanging();
				this._HotPrice = value;
				this.SendPropertyChanged("HotPrice");
				this.OnHotPriceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Isrefinement", DbType="Bit NOT NULL")]
	public bool Isrefinement
	{
		get
		{
			return this._Isrefinement;
		}
		set
		{
			if ((this._Isrefinement != value))
			{
				this.OnIsrefinementChanging(value);
				this.SendPropertyChanging();
				this._Isrefinement = value;
				this.SendPropertyChanged("Isrefinement");
				this.OnIsrefinementChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsHot", DbType="Bit NOT NULL")]
	public bool IsHot
	{
		get
		{
			return this._IsHot;
		}
		set
		{
			if ((this._IsHot != value))
			{
				this.OnIsHotChanging(value);
				this.SendPropertyChanging();
				this._IsHot = value;
				this.SendPropertyChanged("IsHot");
				this.OnIsHotChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDiscount", DbType="Bit NOT NULL")]
	public bool IsDiscount
	{
		get
		{
			return this._IsDiscount;
		}
		set
		{
			if ((this._IsDiscount != value))
			{
				this.OnIsDiscountChanging(value);
				this.SendPropertyChanging();
				this._IsDiscount = value;
				this.SendPropertyChanged("IsDiscount");
				this.OnIsDiscountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoadDate", DbType="DateTime NOT NULL")]
	public System.DateTime LoadDate
	{
		get
		{
			return this._LoadDate;
		}
		set
		{
			if ((this._LoadDate != value))
			{
				this.OnLoadDateChanging(value);
				this.SendPropertyChanging();
				this._LoadDate = value;
				this.SendPropertyChanged("LoadDate");
				this.OnLoadDateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
